### ISSUE TITLE
the problem of dataset

### ISSUE THREAD

**Issue by Chenlulu1993** [wgcban/HyperTransformer#2]
The dataset could not be downloaded using the link you gave.

**Comment by wgcban** [comment]
Hi @Chenlulu1993 

I updated the download links and now it should work. Please let me know if you still can't download it.

Best
Chaminda

**Comment by Chenlulu1993** [comment]
Downloaded successfully, thank you very much!

**Comment by wgcban** [comment]
Nice, I will close this issue.

**Comment by wgcban** [comment]
Nice, I will close this issue.
