### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by who15** [wgcban/HyperTransformer#7]
hello sir,sorry to bother you!  i have a problem about the matlab code,i trying to run the process_pavia.m text but always got the problem of miss the function of disp_rgb,how to fix it?

**Comment by hibryce** [comment]
I got the same problem too. If you dont need RGB pics, just comment out those columns. It works. Hope this could helpful for u`        fig1 = disp_rgb(ref);
        saveas(fig1, strcat(file_name,'/pavia_ref_', num2str(count, '%02d'),'.png'));        saveas(fig2, strcat(file_name,'/pavia_lr_', num2str(count, '%02d'),'.png'));`

**Comment by wgcban** [comment]
@hibryce @who15 
@hibryce Thanks for the answer, this should work. If you still want to visualize RGB image you can use following function.

For pavia:
```
function xrgb = get_rgb(x)
    R=60;
    G=30;
    B=10;

    xr = x(:,:,R);
    xg = x(:,:,G);
    xb = x(:,:,B);
    xrgb = cat(3, xr, xg, xb)/max(x, [], "all");
end

```

 For chikusei:
```
function xrgb = get_rgb(x)
    R=61;
    G=35;
    B=10;

    xr = x(:,:,R);
    xg = x(:,:,G);
    xb = x(:,:,B);
    xrgb = cat(3, xr, xg, xb)/max(x, [], "all");
end

```

**Comment by who15** [comment]
@wgcban @hibryce   thanks for the answer!
